# version 3.8, version tag is depreciated
services:
  fuzzer:
    build: .
    tty: true
    volumes:
      - ./binaries:/app/binaries:ro
      - ./example_inputs:/app/example_inputs:ro
      - ./fuzzer_output:/app/fuzzer_output
    environment:
      - FUZZER_BIN_DIR=/app/binaries
      - FUZZER_SEED_DIR=/app/example_inputs
      - FUZZER_OUT_DIR=/app/fuzzer_output
