version: '3'
services:
  awesome_fuzzer:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./binaries:/app/binaries
      - ./example_inputs:/app/example_inputs
      - ./fuzzer_output:/app/fuzzer_output

