#!/bin/sh
# Wrapper script for starting fuzzers in parallel
# Copyright 2025 Alex Vong
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex

# Install tools
apt-get update
apt-get install -y file parallel

# setup venv
python3 -m venv /app/src/venv
/app/src/venv/bin/pip3 install numpy pikepdf fontTools

# copy binaries and inputs to writable directory
mkdir -p /app/binaries /app/example_inputs
cp -fv /binaries/* /app/binaries
cp -fv /example_inputs/* /app/example_inputs

# decide #jobs to run
if test x"$(nproc)" = x1
then
    njobs=2
else
    njobs=$(nproc)
fi

# call one fuzzer for each binary in parallel
parallel -j $njobs \
         /app/src/venv/bin/python3 /app/src/fuzzer/main.py \
         --bin '{}' --input '/app/example_inputs/{/}.txt' \
         ::: /app/binaries/* \
    || :

# list fuzzer ouputs
ls -ahl /fuzzer_output
